begin;

-- Extensions
create extension if not exists pgcrypto;

-- Role enum for estamparia users.
do $$
begin
  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where t.typname = 'user_role'
      and n.nspname = 'public'
  ) then
    create type public.user_role as enum ('admin', 'atendente', 'producao');
  end if;
end $$;

-- Order status enum.
do $$
begin
  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where t.typname = 'order_status'
      and n.nspname = 'public'
  ) then
    create type public.order_status as enum (
      'em_producao',
      'aguardando_pagamento_50',
      'pagamento_100'
    );
  end if;
end $$;

-- Financial entry enum.
do $$
begin
  if not exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where t.typname = 'financial_entry_type'
      and n.nspname = 'public'
  ) then
    create type public.financial_entry_type as enum ('loss', 'expense');
  end if;
end $$;

-- State table used by the current frontend sync strategy.
create table if not exists public.app_state (
  id text primary key,
  payload jsonb not null,
  updated_at timestamptz not null default now()
);

-- App users linked to auth.users.
create table if not exists public.app_users (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role public.user_role not null default 'atendente',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Suppliers.
create table if not exists public.suppliers (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  contact text not null,
  city text not null default 'Lisboa',
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists suppliers_name_idx on public.suppliers (lower(name));

-- Product attributes.
create table if not exists public.sizes (
  id uuid primary key default gen_random_uuid(),
  label text not null,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create unique index if not exists sizes_label_idx on public.sizes (upper(label));

create table if not exists public.colors (
  id uuid primary key default gen_random_uuid(),
  label text not null,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create unique index if not exists colors_label_idx on public.colors (lower(label));

-- Stock catalog.
create table if not exists public.stock_items (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  size_id uuid not null references public.sizes(id),
  color_id uuid not null references public.colors(id),
  supplier_id uuid not null references public.suppliers(id),
  quantity integer not null default 0 check (quantity >= 0),
  unit_cost numeric(12,2) not null check (unit_cost >= 0),
  reorder_level integer not null default 0 check (reorder_level >= 0),
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists stock_items_variant_unique_idx
  on public.stock_items (lower(name), size_id, color_id, supplier_id);

create index if not exists stock_items_supplier_idx on public.stock_items (supplier_id);
create index if not exists stock_items_reorder_idx on public.stock_items (quantity, reorder_level);

-- Customer orders from atendente to producao.
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_seq bigint generated by default as identity,
  order_number text generated always as ('PED-' || lpad(order_seq::text, 6, '0')) stored,
  client_name text not null,
  contact text not null,
  model text not null,
  quantity integer not null check (quantity > 0),
  size_id uuid not null references public.sizes(id),
  color_id uuid not null references public.colors(id),
  supplier_id uuid not null references public.suppliers(id),
  production_cost numeric(12,2) not null check (production_cost >= 0),
  sale_price numeric(12,2) not null check (sale_price >= 0),
  notes text,
  production_note text,
  status public.order_status not null default 'em_producao',
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists orders_order_seq_idx on public.orders (order_seq);
create unique index if not exists orders_order_number_idx on public.orders (order_number);
create index if not exists orders_status_idx on public.orders (status);
create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_supplier_idx on public.orders (supplier_id);

-- Stock movements.
create table if not exists public.stock_movements (
  id uuid primary key default gen_random_uuid(),
  stock_item_id uuid not null references public.stock_items(id) on delete cascade,
  movement_type text not null check (movement_type in ('add', 'remove', 'order_deduction')),
  amount integer not null check (amount > 0),
  note text,
  order_id uuid references public.orders(id) on delete set null,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create index if not exists stock_movements_stock_item_idx on public.stock_movements (stock_item_id, created_at desc);
create index if not exists stock_movements_order_idx on public.stock_movements (order_id);

-- Losses and expenses.
create table if not exists public.financial_entries (
  id uuid primary key default gen_random_uuid(),
  entry_type public.financial_entry_type not null,
  description text not null,
  amount numeric(12,2) not null check (amount >= 0),
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);

create index if not exists financial_entries_type_idx on public.financial_entries (entry_type);
create index if not exists financial_entries_created_at_idx on public.financial_entries (created_at desc);

-- Generic timestamp update trigger.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists app_users_set_updated_at on public.app_users;
create trigger app_users_set_updated_at
before update on public.app_users
for each row
execute function public.set_updated_at();

drop trigger if exists suppliers_set_updated_at on public.suppliers;
create trigger suppliers_set_updated_at
before update on public.suppliers
for each row
execute function public.set_updated_at();

drop trigger if exists stock_items_set_updated_at on public.stock_items;
create trigger stock_items_set_updated_at
before update on public.stock_items
for each row
execute function public.set_updated_at();

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
before update on public.orders
for each row
execute function public.set_updated_at();

drop trigger if exists app_state_set_updated_at on public.app_state;
create trigger app_state_set_updated_at
before update on public.app_state
for each row
execute function public.set_updated_at();

-- Helper: resolve current app role from app_users.
create or replace function public.current_app_role()
returns public.user_role
language sql
stable
as $$
  select role
  from public.app_users
  where id = auth.uid()
    and is_active = true
  limit 1
$$;

-- Helper predicates for RLS.
create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select coalesce(public.current_app_role() = 'admin', false)
$$;

create or replace function public.is_atendente()
returns boolean
language sql
stable
as $$
  select coalesce(public.current_app_role() = 'atendente', false)
$$;

create or replace function public.is_producao()
returns boolean
language sql
stable
as $$
  select coalesce(public.current_app_role() = 'producao', false)
$$;

-- Apply RLS to all exposed tables.
alter table public.app_users enable row level security;
alter table public.suppliers enable row level security;
alter table public.sizes enable row level security;
alter table public.colors enable row level security;
alter table public.stock_items enable row level security;
alter table public.orders enable row level security;
alter table public.stock_movements enable row level security;
alter table public.financial_entries enable row level security;
alter table public.app_state enable row level security;

-- app_users policies.
drop policy if exists app_users_select_self_or_admin on public.app_users;
create policy app_users_select_self_or_admin
on public.app_users
for select
to authenticated
using (id = auth.uid() or public.is_admin());

drop policy if exists app_users_insert_admin on public.app_users;
create policy app_users_insert_admin
on public.app_users
for insert
to authenticated
with check (public.is_admin());

drop policy if exists app_users_update_admin on public.app_users;
create policy app_users_update_admin
on public.app_users
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- suppliers, sizes and colors: read for all authenticated; write admin only.
drop policy if exists suppliers_select_all_roles on public.suppliers;
create policy suppliers_select_all_roles
on public.suppliers
for select
to authenticated
using (public.is_admin() or public.is_atendente() or public.is_producao());

drop policy if exists suppliers_write_admin on public.suppliers;
create policy suppliers_write_admin
on public.suppliers
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists sizes_select_all_roles on public.sizes;
create policy sizes_select_all_roles
on public.sizes
for select
to authenticated
using (public.is_admin() or public.is_atendente() or public.is_producao());

drop policy if exists sizes_write_admin on public.sizes;
create policy sizes_write_admin
on public.sizes
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists colors_select_all_roles on public.colors;
create policy colors_select_all_roles
on public.colors
for select
to authenticated
using (public.is_admin() or public.is_atendente() or public.is_producao());

drop policy if exists colors_write_admin on public.colors;
create policy colors_write_admin
on public.colors
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- stock items: admin + atendente can read/write, producao read only.
drop policy if exists stock_select_all_roles on public.stock_items;
create policy stock_select_all_roles
on public.stock_items
for select
to authenticated
using (public.is_admin() or public.is_atendente() or public.is_producao());

drop policy if exists stock_write_admin_atendente on public.stock_items;
create policy stock_write_admin_atendente
on public.stock_items
for all
to authenticated
using (public.is_admin() or public.is_atendente())
with check (public.is_admin() or public.is_atendente());

-- orders: admin + atendente create/read/update; producao read/update.
drop policy if exists orders_select_all_roles on public.orders;
create policy orders_select_all_roles
on public.orders
for select
to authenticated
using (public.is_admin() or public.is_atendente() or public.is_producao());

drop policy if exists orders_insert_admin_atendente on public.orders;
create policy orders_insert_admin_atendente
on public.orders
for insert
to authenticated
with check (public.is_admin() or public.is_atendente());

drop policy if exists orders_update_admin_atendente_producao on public.orders;
create policy orders_update_admin_atendente_producao
on public.orders
for update
to authenticated
using (public.is_admin() or public.is_atendente() or public.is_producao())
with check (public.is_admin() or public.is_atendente() or public.is_producao());

drop policy if exists orders_delete_admin_only on public.orders;
create policy orders_delete_admin_only
on public.orders
for delete
to authenticated
using (public.is_admin());

-- stock movements: admin + atendente + producao read, write restricted to admin + atendente.
drop policy if exists stock_movements_select_all_roles on public.stock_movements;
create policy stock_movements_select_all_roles
on public.stock_movements
for select
to authenticated
using (public.is_admin() or public.is_atendente() or public.is_producao());

drop policy if exists stock_movements_write_admin_atendente on public.stock_movements;
create policy stock_movements_write_admin_atendente
on public.stock_movements
for all
to authenticated
using (public.is_admin() or public.is_atendente())
with check (public.is_admin() or public.is_atendente());

-- financial entries: admin only.
drop policy if exists financial_entries_select_admin on public.financial_entries;
create policy financial_entries_select_admin
on public.financial_entries
for select
to authenticated
using (public.is_admin());

drop policy if exists financial_entries_write_admin on public.financial_entries;
create policy financial_entries_write_admin
on public.financial_entries
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- app_state: open for anon/authenticated to support current MVP frontend sync.
drop policy if exists app_state_select_all on public.app_state;
create policy app_state_select_all
on public.app_state
for select
to anon, authenticated
using (true);

drop policy if exists app_state_insert_all on public.app_state;
create policy app_state_insert_all
on public.app_state
for insert
to anon, authenticated
with check (true);

drop policy if exists app_state_update_all on public.app_state;
create policy app_state_update_all
on public.app_state
for update
to anon, authenticated
using (true)
with check (true);

-- Explicit grants for Data API access.
grant usage on schema public to anon, authenticated;
grant select, insert, update on table public.app_state to anon, authenticated;
grant select, insert, update, delete on table public.app_users to authenticated;
grant select, insert, update, delete on table public.suppliers to authenticated;
grant select, insert, update, delete on table public.sizes to authenticated;
grant select, insert, update, delete on table public.colors to authenticated;
grant select, insert, update, delete on table public.stock_items to authenticated;
grant select, insert, update, delete on table public.orders to authenticated;
grant select, insert, update, delete on table public.stock_movements to authenticated;
grant select, insert, update, delete on table public.financial_entries to authenticated;
grant usage, select on all sequences in schema public to authenticated;

commit;
